# Visit https://github.com/lowlighter/metrics for full reference
name: GitHub metrics as SVG image
on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC
    - cron: "0 0 * * *"
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Setup a personal token in your secrets.
          token: ${{ secrets.GH_TOKEN }}

          # Options
          user: trolit
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_followup: no
          plugin_lines: yes
          plugin_habits: yes
          plugin_selfskip: yes
